//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATMDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROBLEM_MANAGEMENT
    {
        public long LOG_SERIAL_NUMBER { get; set; }
        public long TICKET_ID { get; set; }
        public string TERMINAL_ID { get; set; }
        public long WORKFLOW_ID { get; set; }
        public string THIRD_PARTY_TICKET_ID { get; set; }
        public string STATUS { get; set; }
        public string DEVICE_UNIT { get; set; }
        public string PROBLEM_CODE { get; set; }
        public string TASK_GROUP_CODE { get; set; }
        public string TASK_USER_CODE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string CREATE_USER_CODE { get; set; }
        public System.DateTime PROBLEM_START_TIME { get; set; }
        public Nullable<System.DateTime> PROBLEM_END_TIME { get; set; }
        public bool IS_MANUAL { get; set; }
        public string EXPLANATION { get; set; }
        public string UPDATING_CHANNEL_CODE { get; set; }
        public string UPDATING_TRAN_CODE { get; set; }
        public string UPDATING_USER_CODE { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public string RECORD_STATUS { get; set; }
        public string THIRD_PARTY_NAME { get; set; }
        public Nullable<short> MAINTENANCE_LEVEL { get; set; }
        public string REFERANCE_NUMBER { get; set; }
        public string STATUS_LOG_ID { get; set; }
        public string SUPPLY_LOG_ID { get; set; }
    }
}
